#!/bin/bash
# retro-runner.sh — Automated retro extraction from pipeline artifacts
# Usage: retro-runner.sh <feature-name> [--lightweight|--full]
#
# Reads pipeline state, checkpoints, and git log to produce a retro skeleton.
# The agent fills in classifications and qualitative findings after.
set -euo pipefail

FEATURE="${1:?Usage: retro-runner.sh <feature-name> [--lightweight|--full]}"
MODE="${2:---lightweight}"
PIPELINE_DIR=".pipeline"
RETRO_DIR="workflow/retro"
KNOWLEDGE_DIR=".pipeline/heuristics"
TODAY=$(date +%Y-%m-%d)

# --- Validate pipeline exists ---
if [[ ! -d "$PIPELINE_DIR" ]]; then
  echo "ERROR: No pipeline directory found. Run SDD pipeline first."
  exit 1
fi

# --- Collect metrics ---
collect_metrics() {
  local state="$PIPELINE_DIR/state.json"
  local history=0 retries=0

  if [[ -f "$state" ]]; then
    history=$(jq -r '.history | length' "$state" 2>/dev/null || echo "0")
    retries=$(jq -r '[.history[] | select(.direction == "backward")] | length' "$state" 2>/dev/null || echo "0")
  fi

  # Git stats
  local commits=0 loc_added="?" loc_removed="?"
  commits=$(git log --oneline --since="today" --no-merges 2>/dev/null | wc -l | tr -d ' ' || echo "0")
  if [[ "$commits" -gt 0 ]]; then
    loc_added=$(git diff --stat "HEAD~${commits}" 2>/dev/null | tail -1 | grep -oE '[0-9]+ insertion' | cut -d' ' -f1 || echo "?")
    loc_removed=$(git diff --stat "HEAD~${commits}" 2>/dev/null | tail -1 | grep -oE '[0-9]+ deletion' | cut -d' ' -f1 || echo "?")
  fi

  # Files changed
  local files_changed=0
  if [[ "$commits" -gt 0 ]]; then
    files_changed=$(git diff --stat "HEAD~${commits}" 2>/dev/null | tail -1 | grep -oE '[0-9]+ file' | cut -d' ' -f1 || echo "0")
  fi

  cat <<EOF
### Metrics
- Feature: $FEATURE
- Date: $TODAY
- Pipeline transitions: $history
- Retries (backward transitions): $retries
- Commits: $commits
- Files changed: $files_changed
- Lines: +${loc_added} / -${loc_removed}
EOF
}

# --- Extract findings from pipeline state ---
extract_findings() {
  local state="$PIPELINE_DIR/state.json"

  if [[ ! -f "$state" ]]; then
    echo "No pipeline state found."
    return
  fi

  # Backward transitions (failures/retries)
  local backward_count
  backward_count=$(jq -r '[.history[] | select(.direction == "backward")] | length' "$state" 2>/dev/null || echo "0")

  if [[ "$backward_count" -gt 0 ]]; then
    echo "### Retries"
    jq -r '.history[] | select(.direction == "backward") | "- \(.from) → \(.to) (signal: \(.signal))"' "$state" 2>/dev/null || true
    echo ""
  fi

  # Current stage
  local stage
  stage=$(jq -r '.stage // "unknown"' "$state" 2>/dev/null || echo "unknown")
  echo "### Pipeline Status"
  echo "- Final stage: $stage"
  echo ""
}

# --- Extract review findings ---
extract_review() {
  local review_file="$PIPELINE_DIR/checkpoint-review.json"
  if [[ -f "$review_file" ]]; then
    echo "### Review Findings"
    jq -r '.findings // "No findings recorded"' "$review_file" 2>/dev/null || echo "No findings recorded"
    echo ""
  fi
}

# --- Check if full retro is warranted ---
should_run_full() {
  local state="$PIPELINE_DIR/state.json"

  # Complexity >= 8
  local complexity
  complexity=$(jq -r '.complexity // 0' "$state" 2>/dev/null || echo "0")
  if [[ "$complexity" -ge 8 ]]; then
    echo "yes"
    return
  fi

  # Retries >= 2
  local retries
  retries=$(jq -r '[.history[] | select(.direction == "backward")] | length' "$state" 2>/dev/null || echo "0")
  if [[ "$retries" -ge 2 ]]; then
    echo "yes"
    return
  fi

  echo "no"
}

# --- Write retro file ---
write_retro() {
  local retro_file="$RETRO_DIR/$TODAY-$FEATURE.md"
  mkdir -p "$RETRO_DIR"

  cat > "$retro_file" <<EOF
# Retrospective: $FEATURE — $TODAY

$(collect_metrics)

## Findings

$(extract_findings)

$(extract_review)

## Classifications

| Finding | Type | Action |
|---------|------|--------|
| (agent fills in after review) | | |

## Forward Plan
- (populated by agent after review)

---
Mode: $MODE
Generated by: retro-runner.sh
EOF

  echo "$retro_file"
}

# --- Main ---
Retro_FILE=$(write_retro)

echo "Retro written: $Retro_FILE"

# Check if full retro is warranted
if [[ "$MODE" == "--lightweight" ]]; then
  if [[ "$(should_run_full)" == "yes" ]]; then
    echo ""
    echo "NOTICE: Full retro recommended (complexity >= 8 or retries >= 2)"
    echo "Run: bash workflow/pipeline/retro-runner.sh $FEATURE --full"
  fi
fi
